name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  # Job 1: Build and Test (The Gatekeeper)
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node for Server
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install Server Deps
        run: |
          cd server
          npm install

      - name: Install and Build Client
        run: |
          cd client
          npm install
          npm run build
        env:
          CI: false

  # Job 2: Deploy Server
  deploy-server:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Server to Render
        uses: JorgeLNJunior/render-deploy@v1.4.7
        with:
          service_id: ${{ secrets.RENDER_SERVICE_ID_SERVER }}
          api_key: ${{ secrets.RENDER_API_KEY }}
          wait_deploy: true
          
  # Job 3: Deploy Client
  deploy-client:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Client to Render
        uses: JorgeLNJunior/render-deploy@v1.4.7
        with:
          service_id: ${{ secrets.RENDER_SERVICE_ID_CLIENT }}
          api_key: ${{ secrets.RENDER_API_KEY }}
          wait_deploy: true
